### ISSUE TITLE
Submit PR to Arachnid/pyqrencode

### ISSUE THREAD

**Issue by nagromc** [balos1/easy-gpg-to-paper#2]
One of the [project dependencies](https://github.com/cojomojo/easy-gpg-to-paper#dependencies) is [your fork](cojomojo/pyqrencode). We should try to simplify this with a one-liner installation (e.g. `apt-get install libqrencode3 zbar-tools && pip install pyqrencode`)

To avoid needing `git clone https://github.com/cojomojo/pyqrencode.git`, you should submit a PR to [Arachnid/pyqrencode](https://github.com/Arachnid/pyqrencode) from [your fork](cojomojo/pyqrencode).

**Comment by balos1** [comment]
I agree with this, and it is one of my goals. I have just been very busy lately as I am in the middle of a semester at my university so I haven't got to it. I am going to try and do it this weekend.

**Comment by balos1** [comment]
No longer using pyqrencode starting in v0.1.0
