### ISSUE TITLE
Complete README.md

### ISSUE THREAD

**Issue by nagromc** [balos1/easy-gpg-to-paper#3]
From a fresh install of Ubuntu 16.10 Yakety Yak, I stumbled upon multiple missing dependencies and problems. I've tried to keep track of every lack in a [document](https://github.com/nagromc/dotfiles/blob/8a521bae18692ce556ad43a959b62b410d6cbcb2/gnupg/README.md#paperkey-and-qr-code). Maybe you should take a look to complete your README.md :wink:

**Comment by balos1** [comment]
Closed with v0.1.0
