### ISSUE TITLE
How to support >4000 bytes key

### ISSUE THREAD

**Issue by bastien-roucaries** [balos1/easy-gpg-to-paper#7]
Hi,

Debian need to create key > 4000 that does not fit on a single qrcode. 

How can you handle that ?

**Comment by balos1** [comment]
You can pass the number of QR codes to split the key into with the -n flag. For a key that large I’d recommend splitting the key into 8 or more codes.

For example, you can do `gpg2paper.py export -k <KEYID> -n 8 -png --out <NAME>`.
